### ISSUE TITLE
api key hardcoded in code

### ISSUE THREAD

**Issue by M-ZubairAhmed** [kravse/sound-less-dumb#1]
Would you kindly remove the hardcoded key

**Comment by kravse** [comment]
Any suggestions on how to do this without breaking the app and without integrating some sort of paid backend service? Since this app is just an experiment, the API is free, and there's no sensitive user info being exposed I took the simple route. But I'm open to suggestions.

**Comment by M-ZubairAhmed** [comment]
Environment variables, should i send a pr?

**Comment by kravse** [comment]
@M-ZubairAhmed if you don't mind that would be great.

**Comment by kravse** [comment]
I'm actually experimenting with loading in chunked dictionary files rather than using the API so the API key wont be hosted in the repo anymore moving forward.
